version: '3'
services:
  app:
    build: .
    ports:
      - "3004:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=phrmatist_ai
      - DB_USER=root
      - DB_PASS=123456
      - JWT_SECRET=human
      - GEMINI_API_KEY=AIzaSyCL9106qvf8EwjLhxBuGCQ5_E6iDyexjnc
      - LANGCHAIN_API_URL=http://localhost:3004/api
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=phrmatist_ai
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  db_data:
  #services/langchain.service.js